enable = true
requestTimeout = "5s"
parentChainNodeURL = "none"
parentChainConnectionAttempts = 0
sequencerInboxAddress = "none"
extraSignatureCheckingPublicKey = ""
panicOnError = false
disableSignatureChecking = true

[key]
keyDir = ""
privKey = ""

[rpcAggregator]
enable = true
assumedHonest = 1
backends = '''[{"url":"http://localhost:9876","pubkey":"YANNHJokFPJxxsDhJ8u9p9uPN5UDupSM+2I7/GjYfPHQ5X0tPdRnyRosFcXdNPJIhQFdWVWaq3CB4B/FZmoKrwQuzjLzDyNcrnhVMqlfd9PL7iQ0vFI14F7XGyxm64nEIRmaHWxz12lnYiEAt75gBnnMlqN0nrTCQ87OoPaixyKhV7b6OqweMTPiUa+/aFCdhhh0G9f+7O98lxfpQyHek37Wq9zHBfHxvcPlHbNZ6wz9G3phrlLmvqtxhAYlqEVRFxdAzB37sOczDDpeKHgz8AUcSzy/c4DXzQ+guTsajLis0yWrej1tBDky8fD8fHhxzQ6M0TbniTvhHXWLC/eHg5DdHPUvt1v0aC5kjAg1swl3E26z/wo75JcfyBtILiDqhg==","signermask":1}]"'''

[restAggregator]
enable = false
urls = ["http://127.0.0.1:9877"]
onlineUrlList = ""
onlineUrlListFetchInterval = "1h"
strategy = "simple-explore-exploit"
strategyUpdateInterval = "10s"
waitBeforeTryNext = "2s"
maxPerEndpointStats = 20

[restAggregator.simpleExploreExploitStrategy]
exploreIterations = 20
exploitIterations = 1000

[restAggregator.syncToStorage]
checkAlreadyExists = true
eager = false
eagerLowerBoundBlock = 0
retentionPeriod = 9223372036854775807
delayOnError = "1s"
ignoreWriteErrors = true
parentChainBlocksPerRead = 100
stateDir = ""


